---
title: "Federal Research and Development Exploratory Analysis"
author: "YukiKongJu"
date: "26/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyr)
library(dplyr)
library(xts)
library(hrbrthemes)
library(gganimate)

theme_set(theme_bw())

```

## Import Data

```{r cars}

fed_rd <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-12/fed_r_d_spending.csv")
energy_spend <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-12/energy_spending.csv")
climate_spend <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-02-12/climate_spending.csv")

```

## Save Files

```{r echo=false}

folder1 <- "C:/Users/emuli/OneDrive/Documents/R/Projects/tidytuesday/federal_research/data/fed_rd_spending.csv"
folder2 <- "C:/Users/emuli/OneDrive/Documents/R/Projects/tidytuesday/federal_research/data/energy_spending.csv"
folder3 <- "C:/Users/emuli/OneDrive/Documents/R/Projects/tidytuesday/federal_research/data/climate_spending.csv"

write.csv(fed_rd, file = folder1, row.names = FALSE)
write.csv(energy_spend, file = folder2, row.names = FALSE)
write.csv(climate_spend, file = folder3, row.names = FALSE)

```

## Load Data

```{r echo=false}

fed_rd <- read.csv(file = folder1, header = TRUE, sep = ",")
energy_spend <- read.csv(file = folder2, header = TRUE, sep = ",")
climate_spend <- read.csv(file = folder3, header = TRUE, sep = ",")

```

## Data Cleaning

```{r  echo=FALSE}

str(fed_rd)
str(energy_spend)
str(climate_spend)

```

## Data Preprocessing

```{r}

# make ts
fed_rd <- fed_rd %>% 
  as.data.frame()

fed_budget <- fed_rd %>% 
  select(c(year, department, rd_budget)) %>% 
  pivot_wider(names_from = "department", values_from = "rd_budget") %>% 
  as.data.frame()
fed_budget %>%  head()
str(fed_budget)

fed_budget_ts <- xts(fed_budget[,-1], order.by = as.Date(fed_budget[,'year']), format= "%m%y%d")
fed_rd_ts %>% head()

fed_rd_ts <- xts(fed_rd[,-2], order.by = as.Date(fed_rd[,'year']), format= "%m%y%d")

```


## Data Exploration

```{r}

# view department classes
levels(fed_rd$department)
levels(energy_spend$department)
levels(climate_spend$department)

```

### Which Department has the most budget?

```{r}

# autoplot ts

# scatter plot budget by year, president
animate <- fed_rd %>% 
  group_by(department) %>% 
  ggplot(aes(year, rd_budget, color=department))+
  geom_line()+
  geom_point()+
  geom_text(aes(label = department), hjust=-0.5)+
  scale_color_viridis_d()+
  theme(legend.position = "none")+
  labs(x = "Year", y = "Budget ($)", 
       title = "US Federal Budget by Department")

#  subtitle = "Year: {frame_time}"
animate + transition_reveal(year) 

dir <- "C:/Users/emuli/OneDrive/Documents/R/Projects/tidytuesday/federal_research/images/federal_budget.gif"
anim_save(dir)
```


